### ISSUE TITLE
Use Chromium debian package instead of snapshot?

### ISSUE THREAD

**Issue by hashar** [unixpickle/muniverse#4]
`container/Dockerfile` downloads Chrome at revision 464640. Seems that was done because ubuntu 16.04 lacked an up-to-date version at that time.

https://packages.ubuntu.com/xenial/chromium-browser lists chromium 62. Seems that should cover your use case?

**Comment by unixpickle** [comment]
This seems reasonable; will investigate. Perhaps the newer version of Chromium will fix the problems I was having running some WebGL games (a few games were crashing reliably, others periodically). If not, upgrading to Chromium 62 may actually not be worth it since newer versions of Chromium seem to have no way to disable WebGL.
